name: Python Format CI
run-name: Running CI pipeline for ${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Prepare and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Black analysis
        run: |
          black --check .
